/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EducationDetails {
  'major' : string,
  'endDate' : [] | [Time],
  'school' : string,
  'degree' : string,
  'startDate' : Time,
}
export interface Resume {
  'name' : string,
  'educations' : Array<EducationDetails>,
  'email' : string,
  'company' : string,
  'position' : string,
  'workExperiences' : Array<WorkExperienceDetails>,
}
export type Time = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkExperienceDetails {
  'title' : string,
  'endDate' : [] | [Time],
  'description' : string,
  'company' : string,
  'startDate' : Time,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEducation' : ActorMethod<[UserId, EducationDetails], undefined>,
  'addWorkExperience' : ActorMethod<[UserId, WorkExperienceDetails], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Resume]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOwnFullResume' : ActorMethod<[], Resume>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];