/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Time = IDL.Int;
export const EducationDetails = IDL.Record({
  'major' : IDL.Text,
  'endDate' : IDL.Opt(Time),
  'school' : IDL.Text,
  'degree' : IDL.Text,
  'startDate' : Time,
});
export const WorkExperienceDetails = IDL.Record({
  'title' : IDL.Text,
  'endDate' : IDL.Opt(Time),
  'description' : IDL.Text,
  'company' : IDL.Text,
  'startDate' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Resume = IDL.Record({
  'name' : IDL.Text,
  'educations' : IDL.Vec(EducationDetails),
  'email' : IDL.Text,
  'company' : IDL.Text,
  'position' : IDL.Text,
  'workExperiences' : IDL.Vec(WorkExperienceDetails),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEducation' : IDL.Func([UserId, EducationDetails], [], []),
  'addWorkExperience' : IDL.Func([UserId, WorkExperienceDetails], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOwnFullResume' : IDL.Func([], [Resume], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Time = IDL.Int;
  const EducationDetails = IDL.Record({
    'major' : IDL.Text,
    'endDate' : IDL.Opt(Time),
    'school' : IDL.Text,
    'degree' : IDL.Text,
    'startDate' : Time,
  });
  const WorkExperienceDetails = IDL.Record({
    'title' : IDL.Text,
    'endDate' : IDL.Opt(Time),
    'description' : IDL.Text,
    'company' : IDL.Text,
    'startDate' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Resume = IDL.Record({
    'name' : IDL.Text,
    'educations' : IDL.Vec(EducationDetails),
    'email' : IDL.Text,
    'company' : IDL.Text,
    'position' : IDL.Text,
    'workExperiences' : IDL.Vec(WorkExperienceDetails),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEducation' : IDL.Func([UserId, EducationDetails], [], []),
    'addWorkExperience' : IDL.Func([UserId, WorkExperienceDetails], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOwnFullResume' : IDL.Func([], [Resume], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };